msrv = "1.74.0"
# plan API returns Self as an error type for an large-ish enum
large-error-threshold = 256
disallowed-types = [
    { path = "bitcoin::Sequence", reason = "unstable 0.32 sequence, import bitcoin::compat::Sequence" },
    { path = "bitcoin::Weight", reason = "unstable 0.32 weight, import bitcoin::compat::Weight" },
    { path = "bitcoin::absolute::LockTime", reason = "unstable 0.32 absolute locktime, import bitcoin::compat::absolute" },
]
