on: [push, pull_request]

name: Continuous integration

jobs:
  Nightly:
    name: Nightly - Bench + Docs + Fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Crate
        uses: actions/checkout@v2
      - name: Checkout Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Install clippy
        run: rustup component add clippy
      - name: Running benchmarks
        env:
          DO_BENCH: true
        run: ./contrib/test.sh
      - name: Building docs
        env:
          DO_DOCS: true
        run: ./contrib/test.sh
      - name: Running formatter
        env:
          DO_FMT: true
        run: ./contrib/test.sh
      - name: Running linter
        env:
          DO_LINT: true
        run: ./contrib/test.sh

  Integration:                  # 1 job for each bitcoind version we support.
    name: Integration tests - stable toolchain
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        feature:
          [
            "26_0",
            "25_2",
            "25_1",
            "25_0",
            "24_2",
            "24_1",
            "24_0_1",
            "23_2",
            "23_1",
            "23_0",
            "22_1",
            "22_0",
            "0_21_2",
            "0_20_2",
            "0_19_1",
            "0_18_1",
            "0_17_1",
          ]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Select toolchain"
        uses: dtolnay/rust-toolchain@stable
      - name: "Run integration tests"
        run: cd bitcoind-tests && cargo test --features=${{ matrix.feature }}

  Tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust: stable
          - rust: beta
          - rust: nightly
          - rust: "1.56.1"
    steps:
      - name: Checkout Crate
        uses: actions/checkout@v2
      - name: Checkout Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Running cargo
        env:
          DO_FEATURE_MATRIX: true
          DO_NO_STD: true
        run: ./contrib/test.sh

  Embedded:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        run: sudo apt update && sudo apt install -y qemu-system-arm gcc-arm-none-eabi
      - name: Checkout Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rust-src
          target: thumbv7m-none-eabi
      - name: Run
        env:
          RUSTFLAGS: "-C link-arg=-Tlink.x"
          CARGO_TARGET_THUMBV7M_NONE_EABI_RUNNER: "qemu-system-arm -cpu cortex-m3 -machine mps2-an385 -nographic -semihosting-config enable=on,target=native -kernel"
        run: cd embedded && cargo run --target thumbv7m-none-eabi --release
