---   # rust-miniscript CI: If you edit this file please update README.md
on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - 'test-ci/**'
  pull_request:

name: Continuous integration

jobs:
  Stable:
    name: Test - ${{ matrix.toolchain }} toolchain, ${{ matrix.dep }} deps
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, msrv]
        dep: [minimal, recent]
    steps:
      # Cleaning up github bloat so that test feature artifacts don't run out of disk.
      - uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-rbmt
      - name: "Run tests"
        run: cargo rbmt test --toolchain ${{ matrix.toolchain }} --lock-file ${{ matrix.dep }}

  Nightly:
    name: Test - nightly toolchain
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        dep: [minimal, recent]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
        with:
          toolchain: nightly
      - name: "Run tests"
        run: cargo rbmt test nightly --lock-file ${{ matrix.dep }}

  Lint:
    name: Lint - nightly toolchain
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        dep: [recent]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
        with:
          toolchain: nightly
          components: clippy
      - name: "Run lint"
        run: cargo rbmt lint

  Docs:
    name: Docs - stable toolchain
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
        with:
          toolchain: stable
      - name: "Build docs"
        run: cargo rbmt docs

  Docsrs:
    name: Docs - nightly toolchain
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
        with:
          toolchain: nightly
      - name: "Build docs.rs docs"
        run: cargo rbmt docsrs

  Bench:
    name: Bench - nightly toolchain
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
        with:
          toolchain: nightly
      - name: "Run bench"
        run: cargo rbmt bench

  Format:
    name: Format - nightly toolchain
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
        with:
          toolchain: nightly
          components: rustfmt
      - name: "Check formatting"
        run: cargo fmt --all -- --check

  Integration:
    name: Integration tests - stable toolchain
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        feature:
          [
            "30_2",
            "29_0",
            "28_2",
            "27_2",
            "26_2",
            "25_2",
            "24_2",
            "23_2",
            "22_1",
            "0_21_2",
            "0_20_2",
            "0_19_1",
            "0_18_1",
            "0_17_2",
          ]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
        with:
          toolchain: stable
      - name: "Run integration tests"
        run: cargo rbmt integration

  Embedded:
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        run: sudo apt update && sudo apt install -y qemu-system-arm gcc-arm-none-eabi
      - name: Checkout Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rust-src
          target: thumbv7m-none-eabi
      - name: Run
        env:
          RUSTFLAGS: "-C link-arg=-Tlink.x"
          CARGO_TARGET_THUMBV7M_NONE_EABI_RUNNER: "qemu-system-arm -cpu cortex-m3 -machine mps2-an385 -nographic -semihosting-config enable=on,target=native -kernel"
        run: cd embedded && cargo run --target thumbv7m-none-eabi --release
