
name: Shellcheck
on:
  pull_request:
    branches:
      - master
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
      env:
        SHELLCHECK_OPTS: -x # allow outside sources
